### ISSUE TITLE
is lattice a distributive lattice?

### ISSUE THREAD

**Issue by johnynek** [non/algebra#100]
Here we say yes:

"Additionally, join and meet distribute:"

https://github.com/non/algebra/blob/master/core/src/main/scala/algebra/lattice/Lattice.scala#L16

But here we don't test this property:
https://github.com/non/algebra/blob/master/laws/shared/src/main/scala/algebra/laws/LatticeLaws.scala#L39

Lastly, a BoundedLattice is also a rig, right:
https://github.com/non/algebra/blob/master/core/src/main/scala/algebra/lattice/BoundedLattice.scala

we have the distributive + associative laws, we have 0, 1. Am I missing something?

So, the negation (which is identity, it looks like) is somehow only in Bool?

related to #89

**Comment by TomasMikula** [comment]
I think we shouldn't assume lattice to be distributive - there should be a separate `DistributiveLattice` type class for that. (`Heyting` would then extend `DistributiveLattice`.)

As to whether a bounded distributive lattice is a rig: it indeed seems that it is a rig (unless I'm missing something too), but a different one than the one that could be extended to a (Boolean) ring in case of `Bool`. The rig you have in mind defines `plus` as `or`, whereas the ring implied by Bool defines `plus` as `xor`. And we cannot define `xor` without `complement` (or relative complement in case of `Bool` without identity), thus we cannot define `xor` for a general bounded lattice.

**Comment by johnynek** [comment]
closed by #101
