### ISSUE TITLE
more packages?

### ISSUE THREAD

**Issue by johnynek** [non/algebra#105]
we could break core into algebra-core, algebra-ring (depends on core), algebra-lattice (depends on ring).

It might be easier to maintain binary stability in a smaller algebra-core which has fewer concepts, which are incidentally the ones most commonly used in Cats, Algebird, Scalding and Summingbird.

**Comment by avibryant** [comment]
I'd be in favor of this change.

**Comment by rklaehn** [comment]
Isn't this a duplicate of #43? In any case, I would be in favour.

**Comment by non** [comment]
Makes sense to me. Let's do it!

**Comment by johnynek** [comment]
@rklaehn yep. Sorry. My bad. +1 to @non 's original idea.
