### ISSUE TITLE
Eq and PartialOrder instances for List

### ISSUE THREAD

**Issue by ceedubs** [non/algebra#118]
Currently algebra provides an `Order[List[A]]` instance provided that `A` has an `Order` instance. However, it could also provide `Eq[List[A]]` with the weaker constraint that `A` has an `Eq` instance and similarly for `PartialOrder`.

Such [instances](https://github.com/non/cats/blob/692e85501eda19855fcd26e3f661ab9914961b64/core/src/main/scala/cats/std/list.scala#L81-L122) already exist in Cats. They should probably be moved to algebra.

**Comment by johnynek** [comment]
+1

**Comment by non** [comment]
:+1:
