### ISSUE TITLE
Proposal: merge lattice, ring and instances

### ISSUE THREAD

**Issue by johnynek** [non/algebra#160]
Since core was basically converted to be `cats-kernel` there is basically nothing there.

I think there are several reasons for modules:

1. jar size minimization for a la carte usage
2. dependency minimization when some dependencies are only used by a subset of features
3. different stability guarantees (some jar may be experimental).

I don't really see any of those applying anymore with kernel in cats.

I think we should strive for mima-checked stability (turned on CI), but we should merge the projects.

What to call the jar is tricky. Moving classes between artifacts can give some tricky maven issues. In this case, we may move between the same outer project, so maybe it is okay to put them all in algebra-core, since the previous jars depended on core anyway (this is a kind of migration within the existing dependency graph). I think it would be okay to merge all into core.

Any objections to this?

**Comment by non** [comment]
That makes sense to me.
