### ISSUE TITLE
Set instances

### ISSUE THREAD

**Issue by fsvehla** [non/algebra#79]
From cats Gitter:

```
@fsvehla want to open an issue at https://github.com/non/algebra/ ?
```

**Comment by johnynek** [comment]
instances for what? Just everything?

**Comment by non** [comment]
I think in this case the commenter was asking about monoid/semigroup instances for sets.

**Comment by non** [comment]
It looks like we have the following:

 * `Lattice[Set[A]]`
 * `PartialOrder[Set[A]]`
 * `Semiring[Set[A]]`

I think this is actually sufficient. Projects like Cats which want a default `Monoid[Set[A]]` can define it themselves (or use `Semiring[Set[A]].additive`).

**Comment by non** [comment]
Since I opened this issue I'm going to close it, but feel free to disagree and reopen it (along with the type classes that should be added of course).
