### ISSUE TITLE
Add BoolRing type class

### ISSUE THREAD

**Issue by TomasMikula** [non/algebra#98]
This is a proposal to add type class for [_Boolean rings_](https://en.wikipedia.org/wiki/Boolean_ring).

A Boolean ring is a ring that satisfies `x times x = x` for all `x` (i.e. every element is idempotent with respect to multiplication).

There isn't general consensus whether a Boolean ring assumes `1` (multiplicative identity). Some sources refer to Boolean ring as a Boolean algebra without identity. However, since `algebra.ring.Ring` has `1`, it makes sense for `BoolRing` to include `1` as well. Adding a Boolean ring without `1` could be addressed as a separate issue, possibly calling it `BoolRng`.

The above property implies:
 1. Every Boolean ring is a commutative ring.
 2. Every element is its own additive inverse, i.e. `x plus x = 0`.

As a consequence of 1., `BoolRing` should extend `algebra.ring.CommutativeRing`.

As a consequence of 2., `BoolRing` can implement `negate` to be

```scala
def negate(x: A): A = x
```

A Boolean ring is equivalent to a Boolean algebra, with [conversions both ways](https://en.wikipedia.org/wiki/Boolean_ring#Relation_to_Boolean_algebras).

`Bool#asCommutativeRing` already returns a Boolean ring. However, this fact is currently not captured by the return type.

**Comment by johnynek** [comment]
Should we also have a method `.asBooleanAlgebra` or should this also subclass `Bool`?

**Comment by non** [comment]
I slightly prefer `.asBooleanAlgebra`, since it avoids possible ambiguities between a `Bool[A]` and its corresponding `BoolRing[A]` (and also so that `Bool[A].asCommutativeRing.asBooleanAlgebra eq Bool[A]`.

But if you all prefer subclassing I think that would be OK here as well.

**Comment by TomasMikula** [comment]
For a subclassing solution, it would be sufficient for `Bool` to extend `CommutativeRing`&mdash;no `BoolRing` needed. That was my original suggestion. Then @non pointed out that it could conflict with other, more natural implicit rings for the same type.

I will also note that if/when we add the versions without identity (i.e. a Boolean ring without identity, equivalent to a Boolean algebra without identity and relative complement instead of (absolute) complement), whether they are going to be the same type class or two different type classes will have to copy this decision.

I'm fine with either solution.

**Comment by johnynek** [comment]
I tend to agree with @non that subclassing can be difficult when combined with implicit resolution. We do it in some cases, not others, and I guess there is no avoiding the judgement call.

If we did the subclassing route, you could make some wrapper class, `case class BoolInt(toInt: Int)` and define `Bool[BoolInt]` to remove the ambiguity, but this adds boxing costs that I don't see how to remove (insert discussion about zero cost type aliases that give compile errors when misused).

That said, I think the `.as...` approach with the law that it unwraps `y.asX.asY eq y` is a good approach.

**Comment by TomasMikula** [comment]
Yeah, I don't think either design is better in all respects than the other, so I'm OK with taking that route. The type class instances are then free to implement both `Bool` and `BoolRing` by the same instance and have both `asRing` and `asBool` return `this`.

**Comment by TomasMikula** [comment]
Hi, if no-one is working on this yet, I can try to put together a pull request.

**Comment by non** [comment]
Go for it! :)
